#! /usr/bin/env bash

cd $(dirname $0)

if [[ "$1" && -d gen/$1 ]]; then
  rm -rf ~/.qs/script
  cp -R gen/$1 ~/.qs/script
elif [[ $1 ]]; then
  echo "No starter found for '$1'"
  exit 1
else
  rm -rf ~/.qs/script/*
  echo "#! /usr/bin/env bash" > ~/.qs/script/.qs
fi
