#! /usr/bin/env bash

editor=$(which code || which subl || which atom || which vim)

archive=~/.qs/archives/$1
if [[ ! -d $archive ]]; then
  echo "Archive '$1' doesn't exist"
  exit
fi

$editor $archive