#! /usr/bin/env bash

if [[ ! -d ~/.qs/archives/$1 ]]; then
  echo "Archive '$1' doesn't exist"
  exit
fi

echo Restoring from "~/.qs/archives/$1"
rm -rf ~/.qs/script
cp -R ~/.qs/archives/$1 ~/.qs/script

exit 0
